-- =============================================================================
-- Self-signup via OAuth — handle_new_user reorder
-- =============================================================================
-- Esta migration redefinía `auth.handle_new_user` para invertir el orden:
-- antes hacía invitation-first, ahora hace invitation → sino self-signup.
-- Cubre email/password + OAuth (Google/Microsoft) + cualquier otro path.
--
-- La definición consolidada vive en `supabase/sql-extra/auth_setup.sql`.
-- Esta migration ya no la toca porque CREATE FUNCTION en `auth` requiere
-- supabase_admin (postgres no tiene CREATE ahí). Apply: ver header de
-- auth_setup.sql.
--
-- Mantengo este archivo vacío en migrations/ para preservar la historia
-- (la próxima persona que mire `git log` ve qué pasó en este timestamp).
-- =============================================================================
