-- =============================================================================
-- Permitir que service_role llame upsert_integration_credential
-- =============================================================================
-- El seed script corre con SUPABASE_SERVICE_ROLE_KEY (no es un user con
-- JWT) → auth.uid() = NULL → is_platform_admin() devuelve false →
-- function tira "Only platform admins can upsert...".
--
-- Fix: aceptar también auth.role() = 'service_role' (lo manda la JWT
-- del service_role). RLS bypass para service_role ya existe a nivel de
-- la tabla; replicamos esa lógica acá para que el script bootstrap
-- pueda popular las creds iniciales.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.upsert_integration_credential(
  p_provider TEXT,
  p_environment TEXT,
  p_secret_json JSONB,
  p_metadata JSONB DEFAULT '{}'::jsonb,
  p_enabled BOOLEAN DEFAULT false
)
RETURNS UUID
LANGUAGE PLPGSQL
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_row     public.integration_credentials;
  v_sec_id  UUID;
  v_name    TEXT := format('integration:%s:%s', p_provider, p_environment);
BEGIN
  IF NOT (
    public.is_platform_admin()
    OR (SELECT auth.role()) = 'service_role'
  ) THEN
    RAISE EXCEPTION 'Only platform admins can upsert integration credentials';
  END IF;

  SELECT * INTO v_row
    FROM public.integration_credentials
    WHERE provider = p_provider AND environment = p_environment;

  IF v_row.id IS NULL THEN
    v_sec_id := vault.create_secret(p_secret_json::text, v_name, 'auto-generated by upsert_integration_credential');
    INSERT INTO public.integration_credentials (
      provider, environment, enabled, vault_secret_id, metadata
    ) VALUES (
      p_provider, p_environment, COALESCE(p_enabled, false), v_sec_id, COALESCE(p_metadata, '{}'::jsonb)
    )
    RETURNING id INTO v_sec_id;
    RETURN v_sec_id;
  ELSE
    IF v_row.vault_secret_id IS NULL THEN
      v_sec_id := vault.create_secret(p_secret_json::text, v_name, 'auto-generated by upsert_integration_credential');
      UPDATE public.integration_credentials
        SET vault_secret_id = v_sec_id,
            enabled = COALESCE(p_enabled, enabled),
            metadata = COALESCE(p_metadata, metadata)
        WHERE id = v_row.id;
    ELSE
      PERFORM vault.update_secret(v_row.vault_secret_id, p_secret_json::text, v_name);
      UPDATE public.integration_credentials
        SET enabled = COALESCE(p_enabled, enabled),
            metadata = COALESCE(p_metadata, metadata)
        WHERE id = v_row.id;
    END IF;
    RETURN v_row.id;
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.upsert_integration_credential(TEXT, TEXT, JSONB, JSONB, BOOLEAN)
  TO authenticated, service_role;
