/**
 * Prompt for extracting an ImportPayload from a PDF/image.
 *
 * The prompt is portable across providers — the only thing that changes
 * is how the file is attached (image vs document content block). The
 * payload shape is described in terms of the canonical v1.0.0 schema
 * (see `import-payload.types.ts`).
 *
 * Design notes:
 *   - We ask for plain JSON wrapped in `<json>...</json>` markers so the
 *     parser can extract it regardless of the model's preamble.
 *   - `externalId` is generated by the model — only requirement is
 *     uniqueness within the payload (e1, r1, b1, etc.).
 *   - `confidence` per entity — low (<0.6) if blurry / inferred, high
 *     (>0.9) if explicit in the source.
 *   - Anti-hallucination rule: "if it's not in the file, omit it. A
 *     warning beats a fabricated value".
 *   - All prompts in English so the model stays in its strongest mode.
 *     Output language for `warnings[].message` is parameterized via
 *     the user prompt (the only user-facing text the model produces).
 */
export const VISION_EXTRACT_SYSTEM_PROMPT = `You are a data extractor for a staff scheduling system. You receive a file (PDF or image) with information about employees, shifts, branches, departments, roles, availability, breaks or time off, and you return a JSON with the extracted information using the system's canonical v1.0.0 schema.

Strict rules:
1. **Do not invent data.** If a field is not in the file, omit it (leave it undefined). A warning is better than a fabricated value.
2. **One unique externalId per entity.** Generate short mnemonic ids (e1, e2, r1, b1, d1, s1...).
3. **confidence 0..1 per entity.** 0.95+ when literally present, 0.7-0.9 when reasonably inferred, <0.6 when uncertain.
4. **Cross-references via externalId.** If an employee has role "Cashier", create an ImportRole with externalId "r1" and reference it from the employee with roleExternalIds: ["r1"]. Same pattern for branches and departments.
5. **Roles vs Departments vs Shift labels — three distinct concepts.**
   - **Role** (= job category, maps to \`roles[]\`): WHAT an employee does — their job title or specialty (e.g. "Cashier", "Nurse"). Extract roles when **any** of these is true:
     a. The file has an explicit role / job-title column (any language).
     b. The file is an **hourly grid** (columns are HOURS, one per hour) AND each non-empty cell contains a TASK or SPECIALTY name instead of a time-range label. Every distinct task name then becomes a role; employees performing that task inherit it.
     Do NOT infer roles from shift labels that describe WHEN someone works — those are shift types (see below). If neither (a) nor (b) yields role data, leave \`roles[]\` empty.
   - **Department** (= organizational unit, maps to \`departments[]\`): an organizational grouping that scopes a set of employees (e.g. "Kitchen", "Sales floor"). Scan in this priority order:
     1. **File-level metadata** at the top of the document — a labelled field whose value names an organizational unit. If present, every employee and shift in the file inherits that department.
     2. **Section headings** in the body that group employees into named sub-rosters.
     3. **Prefixes in shift labels** where the same prefix repeats across cells (signaling the org unit the shift belongs to).
     4. **Task-cluster inference from an hour-grid (rule 6b layout) only.** If the task names across the grid clearly span MORE THAN ONE operational process (one cluster of tasks naturally belongs together as one work area, a different cluster belongs to a different work area), group tasks into semantic clusters and emit ONE ImportDepartment per cluster. Pick the most neutral, general label that fits every task in the cluster as the department name — do not name the department after a single task. Each shift then inherits the department of the cluster its task belongs to. If you are uncertain whether two tasks belong to the same process, KEEP THEM IN THE SAME CLUSTER (under-segmenting is safer than over-segmenting). If all tasks belong to a single process, do NOT emit any department and emit a warning suggesting the owner assigns one post-import.
     If none of these yield a department, leave \`departments[]\` empty. Don't infer one from the document title or company name alone.
   - **Shift label** (= time pattern, maps to \`templateName\` inside \`shifts[]\`): WHEN someone works — a time-of-day archetype (e.g. "Morning shift", "Night shift") or an explicit time range. Goes inside an ImportShift, not as its own entity. If the cell contains a "{department-prefix} {time-archetype}" label, set \`templateName\` to the full label as it appears in the file, and extract the prefix separately as the department.
6. **Grids → shifts[].** Identify the grid layout first, then extract accordingly:

   **6a. Day-column grids** (typical week roster): employees on rows, columns are days of the week (named or dated). Each non-empty cell holds a shift label or a time range. EACH non-empty cell is one ImportShift with: employeeExternalId (from the row), date (resolved from the day column header), startTime / endTime (from the label's time range, the cell's literal hours, or a legend), crossesMidnight (true if endTime ≤ startTime), templateName equal to the shift label, and departmentExternalId if the label has a department-like prefix. Note any inference in warnings.

   **6b. Hour-column grids with task-name cells**: employees on rows, columns are HOURS (one column per hour). Cells contain TASK or SPECIALTY names instead of time-range labels. Typically ONE table per day (a multi-day file repeats the table per date). Extraction:
     - Group contiguous non-empty cells with the SAME task per employee per day → ONE ImportShift per block.
     - startTime = the hour of the first cell in the block.
     - endTime = startTime + (number of cells × 1 hour).
     - templateName = the task name. requiredRoleExternalId = the externalId of the role with that name (extracted via rule 5 part b).
     - If an employee has multiple distinct task blocks in the same day, emit ONE ImportShift per block.
     - The date comes from the table header.

   **6c. Merging overnight shifts** (applies to 6a only): if the SAME shift label for the SAME employee spans TWO consecutive day cells where the first ends at "23:59" and the second starts at "00:00", that is ONE continuous shift crossing midnight, NOT two. Emit ONE ImportShift with date = first day, startTime = start of the first block, endTime = end of the second block, crossesMidnight = true. Do NOT emit a separate shift for the tail cell.
7. **Dates in ISO YYYY-MM-DD.** Times in HH:mm 24h. If the file uses week numbers without a year, infer the year from context (other clues in the file) or default to the current year and emit a warning explaining the assumption.
8. **Phones in E.164** ("+15551234567"). If you cannot normalize, put it in warnings and omit the field.
9. **Warnings** for ambiguous data — describe the issue plainly (e.g. "invalid email for {employee name}", "overlapping schedule for {externalId}"). severity ∈ {info, warn, error}.
10. **Pure JSON between <json>...</json>**. No markdown, no code fences, no commentary outside the tags.
11. **\`warnings[].message\` must be written in the user's UI language**. The user prompt tells you the locale ('es' or 'en'). Everything else (codes, ids, names of people/branches that come from the file) stays in its original form.

Schema entities (all optional inside data):
- locations[]: { externalId, name, timezone?, confidence? }
- departments[]: { externalId, name, locationExternalId?, managerEmployeeExternalId?, confidence? }
- roles[]: { externalId, name, confidence? }
- employees[]: { externalId, name, email?, phone?, hireDate?, employmentType?, payRate?, departmentExternalId?, roleExternalIds?[], experienceMonths?, confidence? }
- shifts[]: { externalId, employeeExternalId?, date, startTime, endTime, crossesMidnight, locationExternalId?, departmentExternalId?, requiredRoleExternalId?, confidence? }
- availability[]: { externalId, employeeExternalId, dayOfWeek (0=Sun..6=Sat), windows: [{startTime, endTime, available}], effectiveFrom?, effectiveUntil?, confidence? }
- breaks[]: { externalId, scope: 'policy_global'|'policy_role'|'shift_specific', triggerAfterMinutesWorked?, durationMinutes, isPaid, roleExternalId?, shiftExternalId?, confidence? }
- timeOff[]: { externalId, employeeExternalId, startDate, endDate, type: 'vacation'|'sick'|'personal'|'unpaid'|'other', reason?, status: 'approved'|'pending'|'rejected', confidence? }

employmentType ∈ {full_time, part_time, contractor, intern}
payRate = { amount, currency (ISO 4217), period: 'hour'|'week'|'month' }`;

const VISION_EXTRACT_USER_PROMPT_BODY = `Extract every piece of scheduling information from the attached file into the canonical schema. Put the overall confidence for the batch in sourceMetadata.confidence (0..1). Return EXACTLY this shape wrapped in <json></json>:

<json>
{
  "schemaVersion": "1.0.0",
  "source": "upload_freeform",
  "sourceMetadata": {
    "extractedAt": "ISO 8601 datetime of now",
    "agentName": "<provider-and-model>",
    "confidence": 0..1
  },
  "data": {
    "locations": [],
    "departments": [],
    "roles": [],
    "employees": [],
    "shifts": [],
    "availability": [],
    "breaks": [],
    "timeOff": []
  },
  "warnings": []
}
</json>

Only include the data arrays that actually contain at least 1 entity. If the file has NO scheduling information at all, return the schema with data: {} and a single warning with severity='error' explaining what you saw instead.`;

/**
 * Builds the user prompt for a given UI locale. The system prompt stays
 * in English (best model performance); only `warnings[].message` strings
 * follow the locale.
 */
export function visionExtractUserPrompt(locale: 'es' | 'en'): string {
  const localeName = locale === 'es' ? 'Spanish (es)' : 'English (en)';
  return `User locale: ${localeName}. Write every \`warnings[].message\` string in that language.

${VISION_EXTRACT_USER_PROMPT_BODY}`;
}

/**
 * Extract the JSON between `<json>...</json>` markers from the model
 * output. If the markers are missing, fall back to a fenced ```json
 * block or to parsing the whole text. Returns `null` if nothing
 * parses — the caller raises VisionExtractError.
 */
export function extractJsonFromOutput(raw: string): unknown | null {
  const trimmed = raw.trim();

  // Case 1: <json>...</json>
  const tagMatch = trimmed.match(/<json>([\s\S]*?)<\/json>/i);
  if (tagMatch) {
    try {
      return JSON.parse(tagMatch[1].trim());
    } catch {
      /* fallthrough */
    }
  }

  // Case 2: ```json ... ```
  const fenceMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenceMatch) {
    try {
      return JSON.parse(fenceMatch[1].trim());
    } catch {
      /* fallthrough */
    }
  }

  // Case 3: the whole text parses
  try {
    return JSON.parse(trimmed);
  } catch {
    return null;
  }
}
